### ISSUE TITLE
[fetch] use vendir to fetch assets various assets

### ISSUE THREAD

**Issue by cppforlife** [vmware-tanzu/carvel-kapp-controller#12]
kapp-controller was created before [vendir](https://github.com/k14s/vendir). since vendir will have same fetch methods and more, it makes sense to use it in kapp-controller instead of maintaining duplicate code.

**Comment by loewenstein** [comment]
Should we explicitly mention, that vendir will need to support all fetch methods currently supported by App CR? Should there be a corresponding issue in [k14s/vendir/issues](https://github.com/k14s/vendir/issues).

**Comment by ewrenn8** [comment]
Vendir uses [apimachinery v0.19.0](https://github.com/vmware-tanzu/carvel-vendir/blob/0b9720fff72b596c313c10606582218d93bc4afa/go.mod#L23) which uses a lower case import of openapiv2, so we need to do #54 before taking on this one.

**Comment by ewrenn8** [comment]
Added in 5b4bb43

**Comment by cppforlife** [comment]
available in https://github.com/vmware-tanzu/carvel-kapp-controller/releases/tag/v0.14.0
